eureka:
  client:
    serviceUrl:
      defaultZone:http://localhost:9993/Eureka
spring:
  cloud:
    gateway:
      routes:
        - id:microservice-Utilisateur
          uri:lb://MSUtilisateur
          predicates:
            - path= /utilisateur/**
          filter:
            - RewritePath=/utilisateur/(?<path>.*), /$\{path}
            
         - id:microservice-Projet
          uri:lb://MSProjet
          predicates:
            - path= /projet/**
          filter:
            - RewritePath=/projet/(?<path>.*), /$\{path}    
            
